# Generated by Django 5.2.5 on 2025-10-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editors assigned to this publisher.",
                limit_choices_to={"role": "editor"},
                related_name="editor_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Journalists assigned to this publisher.",
                limit_choices_to={"role": "journalist"},
                related_name="journalist_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this publisher (must have role 'publisher').",
                limit_choices_to={"role": "publisher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
