# Generated by Django 5.2.5 on 2025-10-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_options_alter_publisher_editors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Articles included in this newsletter.",
                related_name="newsletters",
                to="articles.article",
            ),
        ),
    ]
