# Generated by Django 5.2.5 on 2025-11-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_newsletter_articles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"verbose_name": "Publisher", "verbose_name_plural": "Publishers"},
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.CharField(
                blank=True,
                help_text="Optional short summary for previews.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="summary",
            field=models.CharField(
                blank=True,
                help_text="Optional short summary for previews.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("editor", "Editor"),
                    ("journalist", "Journalist"),
                    ("publisher", "Publisher"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
    ]
