# Generated by Django 5.2.5 on 2025-11-13 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_customuser_options_alter_publisher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns this publisher (must have role 'publisher').",
                limit_choices_to={"role": "publisher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
